name: trt-llm-bench
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - cudatoolkit
  - pip
  - pip:
      - transformers>=4.42.0
      - accelerate>=0.30.0
      - tqdm>=4.66.0
      - numpy>=1.24.0
      - pandas>=2.2.0
      - matplotlib>=3.8.0
